### ISSUE TITLE
`Plan::new` panics with invalid parameters.

### ISSUE THREAD

**Issue by tlepoint** [zama-ai/concrete-ntt#11]
When trying to construct 

```rust
concrete_ntt::prime64::Plan::try_new(2048, 1024)
```

the programs crashes (instead of returning `None`, as I would have expected):

```
thread 'main' panicked at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:56:13:
assertion failed: t_pow == 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/panicking.rs:127:5
   3: concrete_ntt::roots::sqrt_mod_ex64
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:56:13
   4: concrete_ntt::roots::find_primitive_root64
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/roots.rs:83:22
   5: concrete_ntt::prime64::Plan::try_new
             at /Users/tlepoint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/concrete-ntt-0.1.0/src/prime64.rs:710:16
   6: bug_concrete_ntt::main
             at ./src/main.rs:4:22
   7: core::ops::function::FnOnce::call_once
             at /rustc/bf9a1c8a193fc373897196321215794c8bebbeec/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by IceTDrinker** [comment]
@tlepoint sorry this fell through the cracks !

**Comment by IceTDrinker** [comment]
hello @tlepoint latest concrete-ntt 0.1.1 has a fix for the issue you reported, we'll close this issue, if you encounter any other issue please open a new one on the repo 🙂 

fixed by https://github.com/zama-ai/concrete-ntt/pull/13

cheers

**Comment by tlepoint** [comment]
Awesome, thanks a lot for the fix. Will try it out this week!
